### ISSUE TITLE
Wrong weather info even though the right one exist in the app

### ISSUE THREAD

**Issue by gaining** [fbiego/watch-face-wearfit#3]
Hello, when I press the check button, it shows the right weather temperature but when I click on save, it shows the wrong one. See this video. It demonstrates what my issue is. https://youtube.com/shorts/j1ynWD83RpE 

In the video, 15 degrees was the right temperature.

**Comment by fbiego** [comment]
Thanks for the insight. Apparently, the 15 degree is the average value provided by the API.
The API also provides hourly temperature, which the app picks the value for the hour when you click on save.
The app fetches the weather information at least once a day, and i thought it's best to store the info locally and show based on the current hour

**Comment by gaining** [comment]
Thanks, but is it possible to use the average value provided by the API instead? The stored information is not usually accurate for my location. The more recent measurements are better

**Comment by fbiego** [comment]
That means the temperature will remain the same for the whole day regardless of the hour of day. I would need to restructure the code and provide a way to choose your preference since most people are used to the hourly sync

**Comment by gaining** [comment]
Ok, it's fine to leave it as is then
